package parser

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/Advik-B/Axon/internal/debug"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
	"gopkg.in/yaml.v3"
)

// SaveGraphToFile saves a given Graph struct to a file, automatically
// selecting the correct format based on the output file's extension.
func SaveGraphToFile(graph *Graph, filePath string) error {
	fileExt := filepath.Ext(filePath)
	var outputBytes []byte
	var err error

	switch fileExt {
	case ".ax":
		// Handle JSON format
		jsonMarshaler := protojson.MarshalOptions{
			Indent:        "  ",
			UseProtoNames: true,
		}
		outputBytes, err = jsonMarshaler.Marshal(graph)
		if err != nil {
			return fmt.Errorf("failed to marshal to .ax (JSON): %w", err)
		}

	case ".axb":
		// Handle binary Protobuf format
		outputBytes, err = proto.Marshal(graph)
		if err != nil {
			return fmt.Errorf("failed to marshal to .axb (binary): %w", err)
		}

	case ".axd":
		// Handle commented debug YAML format
		debugGraph := debug.GenerateDebugGraph(graph)
		outputBytes, err = yaml.Marshal(debugGraph)
		if err != nil {
			return fmt.Errorf("failed to marshal to .axd (YAML): %w", err)
		}

	default:
		return fmt.Errorf("unsupported output file extension '%s': must be .ax, .axb, or .axd", fileExt)
	}

	// Write the generated bytes to the file
	return os.WriteFile(filePath, outputBytes, 0644)
}