// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadGraph():Promise<Array<number>>;

export function SaveGraph(arg1:Array<number>):Promise<string>;

export function TranspileCurrentGraph(arg1:Array<number>):Promise<string>;
