// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadGraph() {
  return window['go']['main']['App']['LoadGraph']();
}

export function SaveGraph(arg1) {
  return window['go']['main']['App']['SaveGraph'](arg1);
}

export function TranspileCurrentGraph(arg1) {
  return window['go']['main']['App']['TranspileCurrentGraph'](arg1);
}
